<script setup lang="ts">
import { computed, reactive, ref } from 'vue';
import { LocalRecipeRepository } from '../adapters/local-recipe.repository';
import { NUTRITION, NUTRITION_META, SOURCES, type NutritionType, type SourceType } from '../core/models';
import { createEntry, diagnoses, mealScore, metricsFor, sampleSnapshot } from '../core/recipe-engine';

const repo = new LocalRecipeRepository();
const state = reactive(repo.load());
const tab = ref<'餐盘' | '摄入' | '检测' | '方案' | '报告'>('餐盘');
const notice = ref('');
const draft = reactive({ title: '', source: '文章' as SourceType, nutrition: '深度知识' as NutritionType, minutes: 20, note: '' });
const metrics = computed(() => metricsFor(state.entries));
const score = computed(() => mealScore(metrics.value));
const findings = computed(() => diagnoses(metrics.value));
const recent = computed(() => [...state.entries].sort((a, b) => b.date.localeCompare(a.date)).slice(0, 7));
const totalMinutes = computed(() => state.entries.reduce((sum, item) => sum + item.minutes, 0));
function save() { repo.save({ entries: state.entries, dailyGoal: state.dailyGoal }); }
function addEntry() { state.entries.unshift(createEntry(draft.title, draft.source, draft.nutrition, draft.minutes, draft.note)); save(); draft.title = ''; draft.note = ''; notice.value = '摄入已记录，餐盘已重新计算'; tab.value = '餐盘'; }
function removeEntry(id: string) { state.entries = state.entries.filter((item) => item.id !== id); save(); }
function reset() { const fresh = sampleSnapshot(); state.entries = fresh.entries; state.dailyGoal = fresh.dailyGoal; save(); notice.value = '已恢复初始示例餐盘'; }
</script>

<template>
  <div class="recipe-app"><header class="recipe-topbar"><div class="recipe-brand"><span class="recipe-mark">食</span><div><span class="eyebrow">ATTENTION KITCHEN / 03</span><h1>信息食谱调配师</h1></div></div><div class="recipe-actions"><span>今日已摄入 <b>{{ totalMinutes }}</b> min</span><button type="button" @click="reset">重置演示</button></div></header><main class="recipe-wrap"><section class="recipe-hero"><div><span class="eyebrow coral-text">YOUR DAILY INFORMATION DIET</span><h2>今天，给大脑<br /><em>配一份好食谱。</em></h2><p>信息也有营养密度。记录、咀嚼，再决定下一口要吃什么。</p></div><div class="daily-goal"><span>每日建议摄入</span><strong>{{ state.dailyGoal }}<small>min</small></strong><div><i :style="{ width: `${Math.min(100, totalMinutes / state.dailyGoal * 100)}%` }"></i></div><small>{{ Math.round(totalMinutes / state.dailyGoal * 100) }}% 完成</small></div></section><nav class="recipe-tabs"><button v-for="item in ['餐盘', '摄入', '检测', '方案', '报告']" :key="item" type="button" :class="{ active: tab === item }" @click="tab = item as typeof tab">{{ item }}</button></nav>
      <section v-if="tab === '餐盘'" class="plate-layout"><article class="plate-panel"><div class="section-heading"><div><span class="eyebrow">TODAY'S PLATE</span><h3>今日信息餐盘</h3></div><span class="score-chip">营养均衡度 {{ score }}</span></div><div class="pyramid"><div class="pyramid-level level-1"><span>深度知识</span><b>{{ Math.round((metrics[0]?.share || 0) * 100) }}%</b></div><div class="pyramid-level level-2"><span>行业动态</span><span>技能提升</span></div><div class="pyramid-level level-3"><span>娱乐消遣</span><span>社交信息</span></div></div><div class="pyramid-note"><span>信息营养金字塔</span><p>底层是每天应该稳定摄入的深度内容，上层是有意识调味的轻内容。</p></div></article><aside class="plate-side"><div class="side-card"><span class="eyebrow">NUTRIENT SNAPSHOT</span><h4>营养快照</h4><div v-for="item in metrics" :key="item.nutrition" class="nutrient-row"><div><i :style="{ background: item.color }"></i><span>{{ item.nutrition }}</span></div><strong>{{ item.minutes }}<small>min</small></strong></div></div><div class="side-card insight-card"><span class="eyebrow">KITCHEN NOTE</span><p>“{{ findings[0] }}”</p><button type="button" @click="tab = '检测'">查看完整检测 →</button></div></aside></section>
      <section v-else-if="tab === '摄入'" class="intake-layout"><article class="intake-form"><div class="section-heading"><div><span class="eyebrow">ADD TO THE PLATE</span><h3>记录一次信息摄入</h3></div><span class="section-number">01 / 05</span></div><label>内容标题<input v-model="draft.title" placeholder="例如：一篇关于城市设计的文章" /></label><label>内容形式<select v-model="draft.source"><option v-for="source in SOURCES" :key="source" :value="source">{{ source }}</option></select></label><label>营养类别<select v-model="draft.nutrition"><option v-for="nutrition in NUTRITION" :key="nutrition" :value="nutrition">{{ nutrition }} · {{ NUTRITION_META[nutrition].hint }}</option></select></label><label>消费时长 <output>{{ draft.minutes }} 分钟</output><input v-model.number="draft.minutes" type="range" min="5" max="180" step="5" /></label><label>备注（可选）<textarea v-model="draft.note" rows="3" placeholder="它给你带来了什么？"></textarea></label><button class="coral-button" type="button" @click="addEntry">加入今日餐盘 →</button><p class="notice">{{ notice }}</p></article><article class="intake-list"><div class="section-heading"><div><span class="eyebrow">RECENT BITES</span><h3>最近摄入</h3></div><span class="section-number">{{ state.entries.length }} 条</span></div><div class="bite-list"><div v-for="item in recent" :key="item.id" class="bite-row"><div class="bite-icon" :style="{ background: NUTRITION_META[item.nutrition].color }">{{ NUTRITION_META[item.nutrition].icon }}</div><div><strong>{{ item.title }}</strong><span>{{ item.source }} · {{ item.nutrition }} · {{ item.date }}</span></div><b>{{ item.minutes }}′</b><button type="button" title="删除记录" @click="removeEntry(item.id)">×</button></div></div></article></section>
      <section v-else-if="tab === '检测'" class="diagnosis-layout"><article class="diagnosis-main"><div class="section-heading"><div><span class="eyebrow">DIET DIAGNOSIS</span><h3>你的信息偏食检测</h3></div><span class="score-chip">{{ score }} / 100</span></div><div class="diagnosis-list"><div v-for="(item, index) in findings" :key="item" class="diagnosis-item"><span>0{{ index + 1 }}</span><div><strong>{{ item.includes('偏高') ? '摄入偏高' : item.includes('偏少') ? '长期缺失' : '整体平衡' }}</strong><p>{{ item }}</p></div><i>{{ item.includes('整体') ? '✓' : '!' }}</i></div></div></article><aside class="radar-card"><span class="eyebrow">BALANCE RADAR</span><h4>营养平衡雷达</h4><div class="radar-bars"><div v-for="item in metrics" :key="item.nutrition"><span>{{ item.nutrition }}</span><div><i :style="{ width: `${Math.min(100, item.share / item.target * 100)}%`, background: item.color }"></i></div><small>{{ Math.round(item.share * 100) }}%</small></div></div></aside></section>
      <section v-else-if="tab === '方案'" class="recipe-plan"><div class="section-heading"><div><span class="eyebrow">OPTIMIZED INFORMATION RECIPE</span><h3>下一周的信息食谱</h3></div><span class="section-number">基于最近 7 天</span></div><div class="meal-plan"><div v-for="(item, index) in metrics" :key="item.nutrition" class="meal-item"><span class="meal-time">{{ ['早餐', '上午茶', '午餐', '下午茶', '晚餐'][index] || '加餐' }}</span><div class="meal-color" :style="{ background: item.color }">{{ item.icon }}</div><div><strong>补充 {{ item.nutrition }}</strong><p>{{ item.nutrition === '深度知识' ? '找一篇能让你停下来做笔记的长文。' : item.nutrition === '技能提升' ? '把一个概念变成一次小练习。' : item.nutrition === '行业动态' ? '只选一个可信来源，了解发生了什么。' : item.nutrition === '娱乐消遣' ? '选择能真正让你恢复的轻内容。' : '发一条消息，认真回应一个人。' }}</p></div><span class="meal-duration">{{ Math.max(15, Math.round(item.target * state.dailyGoal)) }} min</span></div></div></section>
      <section v-else class="report-page"><div class="report-head"><span class="eyebrow">WEEKLY INTAKE REPORT · W40</span><h3>你的信息摄入报告</h3><p>信息不是越多越好，而是要吃得刚刚好。</p></div><div class="report-metrics"><div><span>总摄入</span><strong>{{ totalMinutes }}<small>min</small></strong></div><div><span>均衡度</span><strong>{{ score }}<small>/ 100</small></strong></div><div><span>最常摄入</span><strong>{{ metrics.slice().sort((a,b) => b.minutes-a.minutes)[0]?.nutrition }}</strong></div></div><div class="report-bars"><div v-for="item in metrics" :key="item.nutrition" class="report-bar"><div><span>{{ item.nutrition }}</span><b>{{ item.minutes }} min</b></div><div><i :style="{ width: `${Math.max(4, item.share * 100)}%`, background: item.color }"></i><em :style="{ left: `${item.target * 100}%` }"></em></div><small>建议 {{ Math.round(item.target * 100) }}%</small></div></div></section>
    </main></div>
</template>
